### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Madis0**
I hate it when there is a download button that doesn't lead to downloads

### CODE REVIEW

**Comment by RozeFound** [comment]
Isn't better to lead no PyPi project page?

**Comment by Madis0** [comment]
Sure, I didn't know where to look for one.

**Comment by RozeFound** [comment]
https://pypi.org/project/mmc-export

**Comment by RozeFound** [comment]
Now there are 2 buttons that leads to the same thing lol, but ok

**Pull request merged**
